package com.uqac.controllers;

import javafx.fxml.FXML;
//import javafx.fxml.FXMLLoader;

//import java.io.IOException;

import com.uqac.App;

import javafx.event.ActionEvent;
//import javafx.scene.Parent;
//import javafx.scene.Scene;
import javafx.scene.control.MenuItem;
//import javafx.stage.Stage;

public class AccueilAdminController {
	String view;
	String titre;
	@FXML
	private MenuItem GestionAgent;
	@FXML
	private MenuItem GestionClient;
	@FXML
	private MenuItem logout;

	
		@FXML
		public void GestionAgent(ActionEvent event) {
			// TODO Autogenerated
			App app = new App();
			view="GestionAgent";
			titre="GESTION AGENT";
			app.changeView(view, titre);
		}
		
		@FXML
		public void GestionClient(ActionEvent event) {
			// TODO Autogenerated
			App app = new App();
			view="GestionClient";
			titre="GESTION CLIENT";
			app.changeView(view, titre);
		}
		
		@FXML
		public void logout(ActionEvent event) {
			App app = new App();
			view="Login";
			titre="LOGIN";
			app.changeView(view, titre);
		}
}
