package com.uqac.controllers;

import java.time.LocalDate;
import java.util.Date;

import com.uqac.App;
import com.uqac.dao.ClientDao;
import com.uqac.dao.CompteDao;
//import com.uqac.dao.UserDao;
import com.uqac.entities.Client;
//import com.uqac.entities.User;
import com.uqac.entities.Compte;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.DatePicker;
import javafx.scene.control.MenuItem;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;

public class ClientController {
	private String view;
	private String titre;
	private static ClientDao dao = new ClientDao();
	private static CompteDao compteDao = new CompteDao();
	@FXML
	private MenuItem GestionClient;
	@FXML
	private MenuItem Virement;
	@FXML
	private MenuItem Versement;
	@FXML
	private MenuItem Retrait;
	@FXML
	private MenuItem logout;
	@FXML
	private TextField Nom;
	@FXML
	private TextField Prenom;
	@FXML
	private DatePicker DateNaissance;
	@FXML
	private TextField Adresse;
	@FXML
	private TextField NumeroTelephone;
	@FXML
	private Button EnregistrerInfo;


	@FXML
	public void GestionClient(ActionEvent event) {
		// TODO Autogenerated
		App app = new App();
		view="GestionClient";
		titre="GESTION CLIENT";
		app.changeView(view, titre);
	}
	
	@FXML
	public void Virement(ActionEvent event) {
		// TODO Autogenerated
		App app = new App();
		view="Virement";
		titre="VIREMENT";
		app.changeView(view, titre);
	}
	
	@FXML
	public void Versement(ActionEvent event) {
		// TODO Autogenerated
		App app = new App();
		view="Versement";
		titre="VERSEMENT";
		app.changeView(view, titre);
	}
	
	@FXML
	public void Retrait(ActionEvent event) {
		// TODO Autogenerated
		App app = new App();
		view="Retrait";
		titre="RETRAIT";
		app.changeView(view, titre);
	}
	
	
	@FXML
	public void logout(ActionEvent event) {
		App app = new App();
		view="Login";
		titre="LOGIN";
		app.changeView(view, titre);
	}
	
	@FXML
	
	public void EnregistrerInfo (ActionEvent event) {
		
		Compte c = new Compte();
		c.setDate_creation( new Date());
		c.setSolde(0);
		Client client = recupererChamp();
		client = dao.create(client);
		c.setClient(client);
		c=compteDao.create(c);
		client.setCompte(c);
		dao.update(client);
		viderChamp();
	}
	
	private Client recupererChamp() {
		Client client = new Client();

		client.setNom(Nom.getText());
		client.setPrenom(Prenom.getText());
		client.setDate_naiss(java.sql.Date.valueOf(DateNaissance.getValue()));
		client.setAdresse(Adresse.getText());
		client.setTelephone(NumeroTelephone.getText());
		
		return client;
	}
	
	private void viderChamp() {
		Nom.textProperty().set("");
		Prenom.textProperty().set("");
		DateNaissance.setValue(LocalDate.now());
		Adresse.textProperty().set("");
		NumeroTelephone.textProperty().set("");
		
	}

}
